"""add station inventory table

Revision ID: 32f6f0a25059
Revises: 20251124_manual_mapping
Create Date: 2025-11-24 23:25:56.234363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32f6f0a25059'
down_revision: Union[str, None] = '20251124_manual_mapping'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_inventory',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('station_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('quantity_carton', sa.Integer(), nullable=False),
    sa.Column('quantity_pack', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cycle_imports', 'filename',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_column('cycles', 'fixed_station_count')
    op.alter_column('loadsheets', 'revision_diff',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint('station_territory_map_station_id_fkey', 'station_territory_map', type_='foreignkey')
    op.create_foreign_key(None, 'station_territory_map', 'stations', ['station_id'], ['id'])
    op.drop_index('idx_territory_info_code', table_name='territory_info')
    op.drop_constraint('territory_info_code_key', 'territory_info', type_='unique')
    op.create_index(op.f('ix_territory_info_code'), 'territory_info', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_territory_info_code'), table_name='territory_info')
    op.create_unique_constraint('territory_info_code_key', 'territory_info', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_territory_info_code', 'territory_info', ['code'], unique=False)
    op.drop_constraint(None, 'station_territory_map', type_='foreignkey')
    op.create_foreign_key('station_territory_map_station_id_fkey', 'station_territory_map', 'stations', ['station_id'], ['id'], ondelete='CASCADE')
    op.alter_column('loadsheets', 'revision_diff',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('cycles', sa.Column('fixed_station_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('cycle_imports', 'filename',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('station_inventory')
    # ### end Alembic commands ###
