"""Add batch and revision fields for multi-import system

Revision ID: d65288a5dea9
Revises: 3c63b5860231
Create Date: 2025-11-14 00:28:57.407422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd65288a5dea9'
down_revision: Union[str, None] = '3c63b5860231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Eski tabloları drop etme - sadece yeni kolonlar ekle
    op.add_column('loadsheets', sa.Column('batch_number', sa.Integer(), server_default='1', nullable=False))
    op.add_column('loadsheets', sa.Column('loadsheet_type', sqlmodel.sql.sqltypes.AutoString(), server_default='normal', nullable=False))
    op.add_column('loadsheets', sa.Column('revision_diff', sa.Integer(), nullable=True))
    op.add_column('loadsheets', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('import_batch', sa.Integer(), server_default='1', nullable=False))
    op.add_column('orders', sa.Column('is_revision', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('previous_order_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'previous_order_id')
    op.drop_column('orders', 'is_revision')
    op.drop_column('orders', 'import_batch')
    op.drop_column('loadsheets', 'completed_at')
    op.drop_column('loadsheets', 'revision_diff')
    op.drop_column('loadsheets', 'loadsheet_type')
    op.drop_column('loadsheets', 'batch_number')
    op.create_table('Forms',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('Url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK_Forms')
    )
    op.create_table('Contacts',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('RoomNumber', sa.VARCHAR(length=50), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('TitleId', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('OrganizationUnitId', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('OrganizationUnitLevelId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['OrganizationUnitId'], ['OrganizationUnits.Id'], name='FK_Contacts_OrganizationUnits_OrganizationUnitId'),
    sa.ForeignKeyConstraint(['OrganizationUnitLevelId'], ['OrganizationUnitLevels.Id'], name='FK_Contacts_OrganizationUnitLevels_OrganizationUnitLevelId', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['TitleId'], ['titles.id'], name='FK_Contacts_titles_TitleId', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('Id', name='PK_Contacts')
    )
    op.create_index('IX_Contacts_TitleId', 'Contacts', ['TitleId'], unique=False)
    op.create_index('IX_Contacts_OrganizationUnitLevelId', 'Contacts', ['OrganizationUnitLevelId'], unique=False)
    op.create_index('IX_Contacts_OrganizationUnitId', 'Contacts', ['OrganizationUnitId'], unique=False)
    op.create_table('OrganizationUnitLevels',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('LevelNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ParentId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ParentId'], ['OrganizationUnitLevels.Id'], name='FK_OrganizationUnitLevels_OrganizationUnitLevels_ParentId', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('Id', name='PK_OrganizationUnitLevels')
    )
    op.create_index('IX_OrganizationUnitLevels_ParentId', 'OrganizationUnitLevels', ['ParentId'], unique=False)
    op.create_table('Surveys',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK_Surveys'),
    postgresql_ignore_search_path=False
    )
    op.create_table('titles',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('createdat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_titles')
    )
    op.create_table('OrganizationUnits',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('ParentId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('UnitType', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ParentId'], ['OrganizationUnits.Id'], name='FK_OrganizationUnits_OrganizationUnits_ParentId', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('Id', name='PK_OrganizationUnits')
    )
    op.create_index('IX_OrganizationUnits_ParentId', 'OrganizationUnits', ['ParentId'], unique=False)
    op.create_table('AppLinks',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('Url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('IconClass', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('iconpath', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('IsActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('IconPath', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK_AppLinks')
    )
    op.create_table('Documents',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('Url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK_Documents')
    )
    op.create_table('MenuEntries',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('LunchJson', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('DinnerJson', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('UpdatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK_MenuEntries')
    )
    op.create_table('InfoTables',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('TypeId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('Time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('Links', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Images', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('PdfFiles', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['TypeId'], ['EnumType.Id'], name='FK_InfoTables_EnumType_TypeId', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('Id', name='PK_InfoTables')
    )
    op.create_index('IX_InfoTables_TypeId_CreatedAt', 'InfoTables', ['TypeId', sa.text('"CreatedAt" DESC')], unique=False)
    op.create_index('IX_InfoTables_TypeId', 'InfoTables', ['TypeId'], unique=False)
    op.create_table('baskan_id',
    sa.Column('Id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('UnitAddresses',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('Address', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('Phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Website', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('City', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK_UnitAddresses')
    )
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name='PK___EFMigrationsHistory')
    )
    op.create_table('SurveyOptions',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('SurveyQuestionId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['SurveyQuestionId'], ['SurveyQuestions.Id'], name='FK_SurveyOptions_SurveyQuestions_SurveyQuestionId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name='PK_SurveyOptions'),
    postgresql_ignore_search_path=False
    )
    op.create_index('IX_SurveyOptions_SurveyQuestionId', 'SurveyOptions', ['SurveyQuestionId'], unique=False)
    op.create_table('SurveyResponses',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('SurveyId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SurveyQuestionId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SurveyOptionId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['SurveyId'], ['Surveys.Id'], name='FK_SurveyResponses_Surveys_SurveyId', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SurveyOptionId'], ['SurveyOptions.Id'], name='FK_SurveyResponses_SurveyOptions_SurveyOptionId', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SurveyQuestionId'], ['SurveyQuestions.Id'], name='FK_SurveyResponses_SurveyQuestions_SurveyQuestionId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name='PK_SurveyResponses')
    )
    op.create_index('IX_SurveyResponses_SurveyQuestionId', 'SurveyResponses', ['SurveyQuestionId'], unique=False)
    op.create_index('IX_SurveyResponses_SurveyOptionId', 'SurveyResponses', ['SurveyOptionId'], unique=False)
    op.create_index('IX_SurveyResponses_SurveyId', 'SurveyResponses', ['SurveyId'], unique=False)
    op.create_table('EnumType',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('TypeId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['TypeId'], ['EnumType.Id'], name='FK_EnumType_EnumType_TypeId'),
    sa.PrimaryKeyConstraint('Id', name='PK_EnumType')
    )
    op.create_index('IX_EnumType_TypeId', 'EnumType', ['TypeId'], unique=False)
    op.create_table('Menus',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('Items', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK_Menus')
    )
    op.create_table('SurveyQuestions',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('SurveyId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['SurveyId'], ['Surveys.Id'], name='FK_SurveyQuestions_Surveys_SurveyId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name='PK_SurveyQuestions')
    )
    op.create_index('IX_SurveyQuestions_SurveyId', 'SurveyQuestions', ['SurveyId'], unique=False)
    op.create_table('ImportantLinks',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('Url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('IconClass', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('IsActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('IconPath', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK_ImportantLinks')
    )
    # ### end Alembic commands ###
